name: Test
on:
  pull_request:
    paths:
      - '**.php' 
      - '**.yml'
  push:
    paths:
      - '**.php'
      - '**.yml'
jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          extension-csv: mbstring, dom, fileinfo, zip
          coverage: xdebug #optional
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Install Composer dependencies
        run: |
          composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Test
        run: ./vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
